export const CREATE_RECIPE = 'CREATE_RECIPE';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const DELETE_RECIPE_OPTIMISTIC = 'DELETE_RECIPE_OPTIMISTIC';
export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';

export const DELETE_WATER_PROFILE_OPTIMISTIC =
  'DELETE_WATER_PROFILE_OPTIMISTIC';
export const LOAD_WATER_PROFILES_SUCCESS = 'LOAD_WATER_PROFILES_SUCCESS';

export const CREATE_BREW = 'CREATE_BREW';
export const CREATE_BREW_SUCCESS = 'CREATE_BREW_SUCCESS';
export const DELETE_BREW_OPTIMISTIC = 'DELETE_BREW_OPTIMISTIC';
export const LOAD_BREWS_SUCCESS = 'LOAD_BREWS_SUCCESS';
export const UPDATE_BREW_SUCCESS = 'UPDATE_BREW_SUCCESS';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
